[package]
name = "day1"
version = "0.1.0"
edition = "2021"
description = "AoC 2023: Day 1"
authors.workspace = true
documentation.workspace = true
license.workspace = true

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
